steps:
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'meme-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/meme-backend:$COMMIT_SHA'
      - '--region'
      - 'us-west2'
images:
  - 'gcr.io/$PROJECT_ID/meme-backend:$COMMIT_SHA'