version: 'v2.15.1'
services:
  meme-backend:
    image: vangalarajiv/meme-backend
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
            - "meme-backend"
networks:
  backend:
    driver: bridge